name: imple CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a simple command 
      run: echo "This is my pipeline run"

    - name: step 1
      run: echo "This is my frist step 1"

    - name: step 2
      run: echo "This is my second step 2"

    - name: Pipeline Break
      run: echo "pipeline start again"
